name: Release

permissions: {}

on:
  repository_dispatch:
    types: [trigger-release]
  push:
    paths:
      - 'apps/docs/**'
      - '.github/workflows/docs-release.yaml'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]
    steps:
      - name: Obtain token
        id: obtainToken
        uses: tibdex/github-app-token@v2
        with:
          private_key: ${{ secrets.HOMARR_DOCS_RELEASE_APP_PRIVATE_KEY }}
          app_id: ${{ vars.HOMARR_DOCS_RELEASE_APP_ID }}
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          token: ${{ steps.obtainToken.outputs.token }}
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: |
          RAW_TAG="${{ github.event.client_payload.tag }}"
          CLEAN_TAG="${RAW_TAG#v}"
          pnpm -F docs docusaurus docs:version $CLEAN_TAG
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'docs: add version ${{ github.event.client_payload.tag }}'
          push: true
          author_name: "Docs Releases Homarr"
          author_email: "204403377+homarr-docs-releases[bot]@users.noreply.github.com"
          committer_name:  "Docs Releases Homarr"
          committer_email: "204403377+homarr-docs-releases[bot]@users.noreply.github.com"

